Spring:
  application:
    name: yjchoi # projectName
  datasource:
    driver-class-name: org.h2.Driver
    # url: 'jdbc:h2:mem:test'  # In-Memory Mode
    # url: 'jdbc:h2:~/test'  # Embedded Mode
    #DB_CLOSE_DELAY=-1? ?????? ??? ??? ??? ???? ????? ??,
    #DB_CLOSE_ON_EXIT=FALSE? ?????? ?? ? ??????? ?? ??? ??
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # ??? ID ??? ??? ???? ??? ?????.
        # Hibernate 5??? ??? ID ??? ??? ??????, ? ??? ?? ?? ???? ? ??
        use_new_id_generator_mappings: true
        # ??? SQL? ??? ???? ??? ?????.
        # SQL ??? ??? ???? ??? ? ??? ? ? ????
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        # ??? SQL? ?? ?? ????? ??? ?????.
        # true? ???? ???? SQL? ?? ?? ???? ??
        format_sql: true
        # ??? SQL? ??? ???? ??? ?????.
        # true? ???? Hibernate? ??? SQL ??? ??? ??
        show_sql: true

springdoc:
  swagger-ui:
    # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도
    # http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    path: /api-test
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
    operations-sorter: method
  paths-to-match:
    - /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴
